version: 2
jobs:
    build:   
        working_directory: /tmp/repo 
        docker:
            - image: docker:17.09.1-ce-git
        steps:
            - checkout 
            - setup_remote_docker:
                docker_layer_caching: true
                version: 17.05.0-ce
            - run:
                name: Build Docker image
                command: |
                    echo $CIRCLE_BUILD_NUM > /tmp/repo/deployment/version
                    cd src/Website
                    docker build -t monosolutions/awscli:1.0.$CIRCLE_BUILD_NUM -t monosolutions/awscli:latest .
            - run: 
                name: push to repository
                command: |
                    docker login  -u $DOCKER_USER -p $DOCKER_PASS
                    docker push monosolutions/awscli:1.0.$CIRCLE_BUILD_NUM
                    docker push monosolutions/awscli:latest
           